services:
  - type: web
    name: gravity-chat-server
    runtime: node
    region: frankfurt
    plan: free
    rootDir: chat-server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: PORT
        value: 10000
