declare const chrome: any;

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'it';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple translations dictionary (extensible)
const translations: Record<Language, Record<string, string>> = {
    en: {
        'landing.welcome': 'Welcome Back',
        'landing.subtitle': 'Select a network to manage your assets',
        'landing.manage_keys': 'Manage Keys',
        'landing.dapp_browser': 'dApp Browser',
        'wallet.active_key_tooltip': 'Active Key Present',
        'wallet.posting_key_tooltip': 'Posting Key Present',
        'wallet.refresh_tooltip': 'Refresh Balances',
        'wallet.send': 'Send',
        'wallet.receive': 'Receive',
        'wallet.history': 'History',
        'wallet.keys': 'Keys',
        'wallet.network_label': 'Active Network',
        'bulk.analyze': 'Analyze Security',
        'bulk.analyzing': 'Analyzing...',
        'bulk.success': 'Analysis: No risks found.',
        'bulk.switch_network': 'Switch Network',
        // Sidebar
        'sidebar.home': 'Home',
        'sidebar.wallet': 'Wallet',
        'sidebar.bulk': 'Bulk Transfers',
        'sidebar.multisig': 'MultiSig',
        'sidebar.manage': 'Settings',
        'sidebar.lock': 'Lock Wallet',
        'sidebar.pin': 'Detach Window',
        'sidebar.dock': 'Dock Window',
        // Actions
        'action.select_network': 'Select Network',
        'action.manage_keys': 'Manage Keys',
        // Header
        'header.add': 'Add Account',
        'common.cancel': 'Cancel',
        'common.confirm': 'Confirm',
        'common.close': 'Close',
        'common.processing': 'Processing...',
        'common.recent_recipients': 'Recent Recipients',
        'common.account_not_found': 'Account not found',
        // Import
        'import.title': 'Import Wallet',
        'import.manual': 'Manual Entry',
        'import.file': 'Upload File',
        'import.select_chain': 'Select Chain',
        'import.username': 'Username',
        'import.checking': 'Checking chain...',
        'import.found': '✓ Found on Chain',
        'import.not_found': 'Account not found',
        'import.private_keys': 'Private Keys (Paste at least one)',
        'import.key_posting': 'POSTING KEY',
        'import.key_active': 'ACTIVE KEY',
        'import.key_memo': 'MEMO KEY',
        'import.invalid_format': 'Invalid Format',
        'import.save': 'Save Account',
        'import.verifying': 'Verifying Keys...',
        'import.placeholder_username': 'username',
        'import.placeholder_key': 'Starts with 5...',
        // Settings
        'settings.title': 'Configure your wallet',
        'settings.accounts_title': 'Managed Accounts',
        'settings.remove': 'Remove',
        'settings.add_new': 'Add New Account',
        'settings.no_accounts': 'No accounts found.',
        'settings.security_title': 'Security',
        'settings.change_password': 'Change Access Password',
        'settings.biometrics': 'Use Biometrics',
        'settings.reset': 'Reset Wallet',
        // MultiSig
        'multisig.title': 'MultiSig Wallet',
        'multisig.initiator': 'Initiator',
        'multisig.threshold': 'Threshold',
        'multisig.signers': 'Signers',
        'multisig.proposal': 'Proposal',
        'multisig.expiration': 'Expiration',
        'multisig.create': 'Create Proposal',
        'multisig.approve': 'Approve',
        'multisig.construction_title': 'Under Construction...',
        'multisig.construction_desc': 'We are currently building this feature to ensure maximum security and functionality.',
        // Bulk
        'bulk.title': 'Bulk Transfer',
        'bulk.recipients': 'Recipients',
        'bulk.count': 'Count',
        'bulk.check': 'Check Validity',
        'bulk.checking': 'Checking...',
        'bulk.amount': 'Amount',
        'bulk.memo': 'Memo',
        'bulk.same_amount': 'Same Amount',
        'bulk.diff_amount': 'Different Amounts',
        'bulk.add_row': '+ Add Row',
        'bulk.verify': 'Verify',
        'bulk.import': 'Import CSV/TXT',
        'bulk.total': 'Total',
        'bulk.sign_broadcast': 'Sign & Broadcast',
        'bulk.no_accounts': 'No {chain} accounts found.',
        'bulk.sending_from': 'Sending from',
        'bulk.asset': 'Asset:',
        'bulk.available': 'Available:',
        'bulk.title_single': 'Same Amount Distribution',
        'bulk.title_multi': 'Multi-Amount Distribution',
        'bulk.validation_error': 'Validation Error',
        'bulk.error_remove_invalid': 'Please remove invalid accounts before sending.',
        'bulk.success_title': 'Success!',
        'bulk.success_msg': 'Sent {n} transfers successfully. TXID: {txid}...',
        'bulk.error_title': 'Error',
        'bulk.error_failed': 'Failed to send',
        'bulk.warn_not_found': '⚠ Warning: {n} username(s) not found on {chain} chain.',
        'bulk.error_no_active': 'Active key not found for this account.',
        // Lock Screen
        'lock.title': 'Welcome Back',
        'lock.unlock': 'Unlock Wallet',
        'lock.password_placeholder': 'Enter Password',
        'lock.pin_placeholder': 'Enter 6-digit PIN',
        'lock.use_pin': 'Use PIN',
        'lock.use_password': 'Use Password',
        'lock.biometrics': 'Unlock with Biometrics',
        'lock.reset': 'Reset Wallet',
        'lock.confirm_reset': 'Are you sure? This will wipe all data!',
        'lock.create_title': 'Create Master Password',
        'lock.unlock_title': 'Unlock Your Wallet',
        'lock.create_btn': 'Create Wallet',
        'lock.unlock_btn': 'Unlock',
        'lock.processing': 'Processing...',
        'lock.placeholder_create': 'Set Master Password',
        'lock.placeholder_enter': 'Enter Master Password',
        'lock.error_length': 'Password must be at least 8 characters',
        'lock.or_sign_up': 'Or sign up with',
        'lock.or_unlock': 'Or unlock with',
        'lock.clear_reset': 'Clear Local Data & Reset',
        'lock.session_expired': 'Session expired. Please unlock to save changes.',
        'lock.confirm_password': 'Confirm Password',
        'lock.passwords_not_match': 'Passwords do not match',
        'lock.weak': 'Weak',
        'lock.medium': 'Medium',
        'lock.strong': 'Strong',
        'lock.very_strong': 'Very Strong',
        'lock.security_strength': 'Security',
        // Auth
        'auth.authenticator': 'Authenticator App (2FA)',
        'auth.configure_title': 'Setup Authenticator',
        'auth.scan_qr': 'Scan this QR code with Aegis or Google Auth.',
        'auth.enter_code': 'Enter the 6-digit code to verify.',
        'auth.verify': 'Verify',
        'auth.success': 'Authenticator configured successfully!',
        'auth.backup_code': 'Backup Key (Manual Entry)',
        'auth.configure_desc': 'Configure Aegis, Google Auth, or Authy',
        // Sidebar
        'sidebar.language': 'Language',
        // Manage Account
        'manage.title': 'Manage Account',
        'manage.subtitle': '@{name} • {chain}',
        'manage.invalid_posting': 'Invalid Posting Key format',
        'manage.invalid_active': 'Invalid Active Key format',
        'manage.invalid_memo': 'Invalid Memo Key format',
        'manage.validating': 'Validating Keys...',
        'manage.save_verify': 'Save & Verify',
        'manage.remove_link': 'Remove Account',
        'manage.verify_fail': 'Key Validation Failed: ',
        'manage.success': 'Account verified and saved!',
        'manage.confirm_remove_title': 'Remove @{name}?',
        'manage.confirm_remove_desc': 'This will remove the account keys. Cannot be undone.',
        'manage.cancel': 'Cancel',
        'manage.confirm_remove': 'Remove',
        'manage.add_posting': 'Add Posting Private Key',
        'manage.add_active': 'Add Active Private Key',
        'manage.add_memo': 'Add Memo Private Key',
        // New Import Keys
        'import.success_file_parsed': 'File parsed. Accounts found: ',
        'import.error_file_read': 'Error reading file.',
        'import.drag_drop': 'Drag & Drop JSON/CSV/TXT file',
        'import.click_upload': 'or click to upload',
        'import.processing': 'Processing...',
        'import.bulk_summary': 'Imported {count} accounts.',
        'import.no_valid_accounts': 'No valid accounts found in file.',
        // Security
        'security.analysis_prompt': 'Please analyze this crypto transaction for safety risks in English: ',

        'history.title': 'History: {user}',
        'history.loading': 'Loading history...',
        'history.empty': 'No transfers found in recent history.',
        'history.received': 'Received',
        'history.sent': 'Sent',
        'history.from': 'From',
        'history.to': 'To',

        // Sign Request
        'sign.title': 'Signature Request',
        'sign.transfer_title': 'Transfer Request',
        'sign.vote_title': 'Vote Request',
        'sign.custom_json_title': 'Custom JSON',
        'sign.operation': 'Operation',
        'sign.params': 'Parameters',
        'sign.author': 'Author',
        'sign.weight': 'Weight',
        'sign.id': 'ID',
        'sign.json_payload': 'Payload',
        'sign.from': 'From',
        'sign.to': 'To',
        'sign.reject': 'Reject',
        'sign.confirm': 'Confirm',
        'sign.signing': 'Signing...',
        'sign.local_file': 'Local File',
        'sign.unknown_source': 'Unknown Source',
        'sign.loading': 'Loading request...',
        'sign.error': 'Error',
        'sign.account_not_found': 'Account not found in this wallet.',
        'sign.keys_missing': 'Keys missing for this account.',
        'sign.user_rejected': 'User rejected request',
        'sign.success': 'Signed successfully',
        'sign.trust_domain': 'Trust this site (Don\'t ask again)',

        // Errors
        'validation.invalid_amount': 'Please enter a valid amount greater than 0.',
        'validation.required': 'All fields are required.',
        'validation.account_not_found': 'Account not found on {chain}',

        // Transfer Review
        'transfer.available': 'Available:',
        'transfer.memo_placeholder': 'Public note',
        'transfer.review_title': 'Confirm Transfer',
        'transfer.review_btn': 'Review Transfer',
        'transfer.back': 'Back',
        'transfer.total_amount': 'Total Amount',
        'transfer.per_user': 'Per User:',
        'transfer.please_review': 'Please review carefully.',
        'transfer.operations': 'Operations',
        'transfer.no_memo': 'No Memo',
        'transfer.optional': '(Optional)',
        // Receive Modal
        'receive.title': 'Receive Funds',
        'receive.scan_qr': 'Scan QR to send {chain} to this account',
        'receive.account_name': 'Account Name',
        'receive.copied': 'Copied!',
        'receive.copy': 'Copy',
        'receive.close': 'Close',
        // Manage Keys Extra
        'manage.label_posting': 'Posting Key',
        'manage.label_active': 'Active Key',
        'manage.label_memo': 'Memo Key',
        // Import Errors Extra
        'import.error_username': 'Please enter a valid, existing username.',
        'import.error_format': 'One or more keys have an invalid format.',
        'import.error_missing_key': 'You must provide at least one private key.',
        'import.match_error_posting': 'Posting Key does not match the account on chain.',
        'import.match_error_active': 'Active Key does not match the account on chain.',
        'import.match_error_memo': 'Memo Key does not match the account on chain.',
        // Sign Request Extra
        'sign.expired': 'Request expired or not found',
        'sign.active_key_missing': 'Active Key missing',
        'sign.key_missing_type': '{type} key missing for this account',
        'sign.key_missing_generic': '{type} key missing',
        'sign.buffer_title': 'Sign Message',
        'sign.message_label': 'Message',
        'sign.key_type': 'Key',
        // Help Guide
        'help.title': 'User Guide',
        'help.keys_title': 'Managing Keys',
        'help.keys_desc': 'Your account security depends on your keys. Never share your Master Password or Private Keys.',
        'help.posting_key_label': 'Posting Key',
        'help.posting_key_desc': 'Use this for social actions like voting, posting, and following.',
        'help.active_key_label': 'Active Key',
        'help.active_key_desc': 'Required for financial transactions like transfers and power ups.',
        'help.memo_key_label': 'Memo Key',
        'help.memo_key_desc': 'Used to encrypt and decrypt private messages.',
        'help.transactions_title': 'Transactions',
        'help.transactions_desc': 'Easily manage your assets across multiple chains.',
        'help.transfers_point': 'Send funds to any user securely.',
        'help.history_point': 'View incoming and outgoing transfers.',
        'help.bulk_point': 'Use Bulk Transfer for mass distributions.',
        'help.power_title': 'Power & Staking',
        'help.power_desc': 'Put your tokens to work by staking them (Powering Up).',
        'help.power_point': 'Power Up to increase your voting influence and earn more rewards.',
        'help.power_down_point': 'Power Down converts Power back to tokens over 13 weeks.',
        'help.delegate_point': 'Delegate Power to others without losing ownership.',
        'help.savings_title': 'Savings & RCs',
        'help.savings_desc': 'Advanced chain features for Hive and Steem.',
        'help.savings_point': 'Deposit HBD/SBD to Savings to earn interest (3-day withdraw notice).',
        'help.rc_point': 'Delegate Resource Credits (Hive only) to help new users transacting.',
        'help.security_title': 'Security First',
        'help.security_desc': 'Transactions are signed locally. Your keys never leave your device unencrypted.',
        'help.chat_title': 'Gravity Live Chat',
        'help.chat_desc': 'Real-time messaging with custom rooms and DMs.',
        'help.chat_warning': 'This chat uses a unique ID separate from your blockchain wallets.',
        'help.chat_cost': 'Free & Instant (Off-chain)',
        // Help Buttons
        'help.btn_home': 'Return to the main screen to select a network.',
        'help.btn_wallet': 'Access your accounts, balances, and actions.',
        'help.btn_bulk': 'Send funds to multiple accounts in a single transaction.',
        'help.btn_multisig': 'Manage multi-signature accounts (Coming Soon).',
        'help.btn_settings': 'Configure accounts, security, and preferences.',
        'help.btn_lock': 'Lock your wallet immediately.',
        'help.btn_detach': 'Open the wallet in a separate floating window.',
        'help.btn_send': 'Transfer funds to another user.',
        'help.btn_receive': 'Show QR code to receive funds.',
        'help.btn_history': 'View your recent transaction history.',
        'help.btn_keys': 'View and manage your private keys.',
        'help.btn_powerup': 'Convert tokens to Power to increase voting influence.',
        'help.btn_powerdown': 'Start the 13-week power down process.',
        'help.btn_delegate': 'Delegate your Power to another account.',
        'help.btn_savings': 'Deposit stablecoins to earn interest (Hive/Steem only).',
        'help.btn_rc': 'Delegate Resource Credits to help others transact (Hive only).',
        // Power Operations
        'power.powerup_title': 'Power Up',
        'power.powerdown_title': 'Power Down',
        'power.delegate_title': 'Delegate Power',
        'power.powerup_desc': 'Convert {token} to {power} to increase your voting power',
        'power.powerdown_desc': 'Start powering down your {power} (13 weeks process)',
        'power.delegate_desc': 'Delegate your {power} to another account',
        'power.from_account': 'From Account',
        'power.recipient': 'Recipient',
        'power.recipient_placeholder': 'username',
        'power.recipient_hint': 'Leave as your username to power up yourself',
        'power.delegatee': 'Delegate To',
        'power.delegatee_placeholder': 'username',
        'power.amount_token': 'Amount ({token})',
        'power.amount_vests': 'Amount ({power})',
        'power.powerup_hint': 'This will convert {token} to {power}',
        'power.powerdown_hint': 'Enter amount in {power} to power down',
        'power.delegate_hint': 'Enter amount in {power} to delegate',
        'power.invalid_amount': 'Please enter a valid amount',
        'power.invalid_recipient': 'Please enter a valid recipient',
        'power.active_key_required': 'Active key is required for this operation',
        'power.operation_failed': 'Operation failed',
        'power.success': 'Operation successful!',
        'power.stop_powerdown': 'Stop Power Down',
        'power.stop_powerdown_warning': 'This will cancel your active power down. Click Confirm to proceed.',
        'power.available_power': 'Available {power}',
        // Savings Operations
        'savings.deposit_title': 'Deposit to Savings',
        'savings.withdraw_title': 'Withdraw from Savings',
        'savings.deposit_desc': 'Earn interest by depositing {token} to savings',
        'savings.withdraw_desc': 'Withdraw {token} from savings (3 days waiting period)',
        'savings.account': 'Account',
        'savings.amount': 'Amount ({token})',
        'savings.deposit_hint': 'Funds will be available for withdrawal after 3 days',
        'savings.withdraw_hint': 'Withdrawal will be processed after 3 days',
        'savings.deposit_info': 'Savings earn interest and have a 3-day withdrawal period for security',
        'savings.withdraw_info': 'Withdrawals take 3 days to process. You can cancel during this time.',
        'savings.invalid_amount': 'Please enter a valid amount',
        'savings.active_key_required': 'Active key is required for this operation',
        'savings.operation_failed': 'Operation failed',
        'savings.success': 'Operation successful!',
        'savings.not_available': 'Not Available',
        'savings.blurt_not_supported': 'Blurt does not support savings feature',

        // RC Operations
        'rc.hive_only': 'Resource Credits (RC) delegation is only available on the Hive blockchain.',
        'rc.delegate_title': 'Delegate Resource Credits',
        'rc.undelegate_title': 'Undelegate Resource Credits',
        'rc.delegate_desc': 'Help new accounts by delegating them Resource Credits.',
        'rc.undelegate_desc': 'Stop delegating RC to an account.',
        'rc.from_account': 'From Account',
        'rc.delegatee': 'Delegate To',
        'rc.delegatee_placeholder': 'username',
        'rc.max_rc': 'RC Amount',
        'rc.max_rc_hint': 'Enter the amount of RC you want to delegate.',
        'rc.invalid_delegatee': 'Please enter a valid delegatee username',
        'rc.invalid_amount': 'Please enter a valid RC amount',
        'rc.active_key_required': 'Active key is required for RC delegation',
        'rc.operation_failed': 'RC Operation failed',
        'rc.success': 'RC delegation updated successfully!',
        'rc.not_available': 'RC Not Available',
        'rc.delegate_info': 'Delegating RC allows accounts to perform more operations on Hive.',
        'rc.undelegate_info': 'This will remove the RC delegation from this account.',
    },
    es: {
        'landing.welcome': 'Bienvenido',
        'landing.subtitle': 'Selecciona una red para gestionar tus activos',
        'landing.manage_keys': 'Gestionar Llaves',
        'landing.dapp_browser': 'Navegador dApp',
        'wallet.active_key_tooltip': 'Llave Activa Presente',
        'wallet.posting_key_tooltip': 'Llave Posting Presente',
        'wallet.refresh_tooltip': 'Actualizar Saldos',
        'wallet.send': 'Enviar',
        'wallet.receive': 'Recibir',
        'wallet.history': 'Historial',
        'wallet.keys': 'LLAVES',
        'wallet.no_accounts_chain': 'No hay cuentas añadidas para {chain}',
        'wallet.add_one': 'Añadir Cuenta',
        'wallet.network_label': 'Red Activa',
        'bulk.analyze': 'Analizar Seguridad',
        'bulk.analyzing': 'Analizando...',
        'bulk.success': 'Análisis: Sin riesgos detectados.',
        'bulk.switch_network': 'Cambiar Red',
        // Sidebar
        'sidebar.home': 'Inicio',
        'sidebar.wallet': 'Billetera',
        'sidebar.bulk': 'Transf. Masiva',
        'sidebar.multisig': 'Multi-firma',
        'sidebar.manage': 'Configuración',
        'sidebar.lock': 'Bloquear',
        'sidebar.pin': 'Desanclar Ventana',
        'sidebar.dock': 'Anclar Ventana',
        // Actions
        'action.select_network': 'Seleccionar Red',
        'action.manage_keys': 'Administrar Llaves',
        // Header
        'header.add': 'Añadir Cuenta',
        'common.cancel': 'Cancelar',
        'common.confirm': 'Confirmar',
        'common.close': 'Cerrar',
        'common.processing': 'Procesando...',
        'common.recent_recipients': 'Recipientes Recientes',
        'common.account_not_found': 'Cuenta no encontrada',
        // Import
        'import.title': 'Importar Billetera',
        'import.manual': 'Entrada Manual',
        'import.file': 'Subir Archivo',
        'import.select_chain': 'Seleccionar Red',
        'import.username': 'Usuario',
        'import.checking': 'Comprobando red...',
        'import.found': '✓ Encontrado',
        'import.not_found': 'Cuenta no encontrada',
        'import.private_keys': 'Llaves Privadas (Pegar al menos una)',
        'import.key_posting': 'LLAVE POSTING',
        'import.key_active': 'LLAVE ACTIVA',
        'import.key_memo': 'LLAVE MEMO',
        'import.invalid_format': 'Formato Inválido',
        'import.save': 'Guardar Cuenta',
        'import.verifying': 'Verificando...',
        'import.placeholder_username': 'nombre de usuario',
        'import.placeholder_key': 'Comienza con 5...',
        // Settings
        'settings.title': 'Configura tu wallet',
        'settings.accounts_title': 'Cuentas Gestionadas',
        'settings.remove': 'Eliminar',
        'settings.add_new': 'Añadir Nueva Cuenta',
        'settings.no_accounts': 'No hay cuentas encontradas.',
        'settings.security_title': 'Seguridad',
        'settings.change_password': 'Cambiar Contraseña',
        'settings.biometrics': 'Usar Biometría',
        'settings.reset': 'Reiniciar Billetera',
        // MultiSig
        'multisig.title': 'Billetera Multi-firma',
        'multisig.initiator': 'Iniciador',
        'multisig.threshold': 'Umbral',
        'multisig.signers': 'Firmantes',
        'multisig.proposal': 'Propuesta',
        'multisig.expiration': 'Expiración',
        'multisig.create': 'Crear Propuesta',
        'multisig.approve': 'Aprobar',
        'multisig.construction_title': 'En Construcción...',
        'multisig.construction_desc': 'Estamos construyendo esta funcionalidad para asegurar la máxima seguridad.',
        // Bulk
        'bulk.title': 'Transferencia Masiva',
        'bulk.recipients': 'Destinatarios',
        'bulk.count': 'Recuento',
        'bulk.check': 'Verificar Validez',
        'bulk.checking': 'Comprobando...',
        'bulk.amount': 'Cantidad',
        'bulk.memo': 'Memo',
        'bulk.same_amount': 'Misma Cantidad',
        'bulk.diff_amount': 'Cantidades Diferentes',
        'bulk.add_row': '+ Añadir Fila',
        'bulk.verify': 'Verificar',
        'bulk.import': 'Importar CSV/TXT',
        'bulk.total': 'Total',
        'bulk.sign_broadcast': 'Firmar y Transmitir',
        'bulk.no_accounts': 'No se encontraron cuentas de {chain}.',
        'bulk.sending_from': 'Enviando desde',
        'bulk.asset': 'Activo:',
        'bulk.available': 'Disponible:',
        'bulk.title_single': 'Distribución Misma Cantidad',
        'bulk.title_multi': 'Distribución Cantidades Múltiples',
        'bulk.validation_error': 'Error de Validación',
        'bulk.error_remove_invalid': 'Por favor elimina las cuentas inválidas antes de enviar.',
        'bulk.success_title': '¡Éxito!',
        'bulk.success_msg': 'Enviadas {n} transferencias exitosamente. TXID: {txid}...',
        'bulk.error_title': 'Error',
        'bulk.error_failed': 'Error al enviar',
        'bulk.warn_not_found': '⚠ Advertencia: {n} usuario(s) no encontrado(s) en la red {chain}.',
        'bulk.error_no_active': 'No se encontró llave activa para esta cuenta.',
        // Lock Screen
        'lock.title': 'Bienvenido',
        'lock.unlock': 'Desbloquear',
        'lock.password_placeholder': 'Contraseña',
        'lock.pin_placeholder': 'PIN de 6 dígitos',
        'lock.use_pin': 'Usar PIN',
        'lock.use_password': 'Usar Contraseña',
        'lock.biometrics': 'Usar Biometría',
        'lock.reset': 'Reiniciar Billetera',
        'lock.confirm_reset': '¿Seguro? ¡Se borrarán los datos!',
        'lock.create_title': 'Crear Contraseña Maestra',
        'lock.unlock_title': 'Desbloquear Billetera',
        'lock.create_btn': 'Crear Billetera',
        'lock.unlock_btn': 'Desbloquear',
        'lock.processing': 'Procesando...',
        'lock.placeholder_create': 'Establecer Contraseña',
        'lock.placeholder_enter': 'Introducir Contraseña',
        'lock.error_length': 'La contraseña debe tener al menos 8 caracteres',
        'lock.or_sign_up': 'O regístrate con',
        'lock.or_unlock': 'O desbloquea con',
        'lock.clear_reset': 'Borrar Datos Locales y Reiniciar',
        'lock.session_expired': 'Sesión expirada. Desbloquea para guardar cambios.',
        'lock.confirm_password': 'Confirmar Contraseña',
        'lock.passwords_not_match': 'Las contraseñas no coinciden',
        'lock.weak': 'Débil',
        'lock.medium': 'Media',
        'lock.strong': 'Fuerte',
        'lock.very_strong': 'Muy Fuerte',
        'lock.security_strength': 'Seguridad',
        // Auth
        'auth.authenticator': 'Aplicación Autenticadora (2FA)',
        'auth.configure_title': 'Configurar Autenticador',
        'auth.scan_qr': 'Escanea este QR con Aegis o Google Auth.',
        'auth.enter_code': 'Ingresa el código de 6 dígitos para verificar.',
        'auth.verify': 'Verificar',
        'auth.success': '¡Autenticador configurado exitosamente!',
        'auth.backup_code': 'Clave de Respaldo (Entrada Manual)',
        'auth.configure_desc': 'Configura Aegis, Google Auth, o Authy',
        // Sidebar
        'sidebar.language': 'Idioma',
        // Manage Account
        'manage.title': 'Gestionar Cuenta',
        'manage.subtitle': '@{name} • {chain}',
        'manage.invalid_posting': 'Formato de Llave Posting Inválido',
        'manage.invalid_active': 'Formato de Llave Activa Inválido',
        'manage.invalid_memo': 'Formato de Llave Memo Inválido',
        'manage.validating': 'Validando Llaves...',
        'manage.save_verify': 'Guardar y Verificar',
        'manage.remove_link': 'Eliminar Cuenta',
        'manage.verify_fail': 'Validación Fallida: ',
        'manage.success': '¡Cuenta verificada y guardada!',
        'manage.confirm_remove_title': '¿Eliminar @{name}?',
        'manage.confirm_remove_desc': 'Esto eliminará las llaves de la cuenta. No se puede deshacer.',
        'manage.cancel': 'Cancelar',
        'manage.confirm_remove': 'Eliminar',
        'manage.add_posting': 'Añadir Llave Privada Posting',
        'manage.add_active': 'Añadir Llave Privada Activa',
        'manage.add_memo': 'Añadir Llave Privada Memo',
        // New Import Keys
        'import.success_file_parsed': 'Archivo analizado. Cuentas: ',
        'import.error_file_read': 'Error al leer archivo.',
        'import.drag_drop': 'Arrastra archivo JSON/CSV/TXT',
        'import.click_upload': 'o click para subir',
        'import.processing': 'Procesando...',
        'import.bulk_summary': 'Importadas {count} cuentas.',
        'import.no_valid_accounts': 'No se encontraron cuentas válidas.',
        // Security
        'security.analysis_prompt': 'Por favor analiza esta transacción en busca de riesgos en Español: ',

        'history.title': 'Historial: {user}',
        'history.loading': 'Cargando historial...',
        'history.empty': 'No se encontraron transferencias recientes.',
        'history.received': 'Recibido',
        'history.sent': 'Enviado',
        'history.from': 'De',
        'history.to': 'Para',

        // Sign Request
        'sign.title': 'Solicitud de Firma',
        'sign.transfer_title': 'Solicitud de Transferencia',
        'sign.vote_title': 'Solicitud de Voto',
        'sign.custom_json_title': 'JSON Personalizado',
        'sign.operation': 'Operación',
        'sign.params': 'Parámetros',
        'sign.author': 'Autor',
        'sign.weight': 'Peso',
        'sign.id': 'ID',
        'sign.json_payload': 'Contenido (Payload)',
        'sign.from': 'De',
        'sign.to': 'Para',
        'sign.reject': 'Rechazar',
        'sign.confirm': 'Confirmar',
        'sign.signing': 'Firmando...',
        'sign.local_file': 'Archivo Local',
        'sign.unknown_source': 'Fuente Desconocida',
        'sign.loading': 'Cargando solicitud...',
        'sign.error': 'Error',
        'sign.account_not_found': 'Cuenta no encontrada en esta billetera.',
        'sign.keys_missing': 'Faltan llaves para esta cuenta.',
        'sign.user_rejected': 'El usuario rechazó la solicitud',
        'sign.success': 'Firmado exitosamente',
        'sign.trust_domain': 'Confiar en este sitio (No volver a preguntar)',

        // Errors
        'validation.invalid_amount': 'Por favor ingresa una cantidad válida mayor a 0.',
        'validation.required': 'Todos los campos son obligatorios.',
        'validation.account_not_found': 'Cuenta no encontrada en {chain}',

        // Transfer Review
        'transfer.available': 'Disponible:',
        'transfer.memo_placeholder': 'Nota pública',
        'transfer.review_title': 'Confirmar Envío',
        'transfer.review_btn': 'Revisar Transferencia',
        'transfer.back': 'Atrás',
        'transfer.total_amount': 'Cantidad Total',
        'transfer.per_user': 'Por Usuario:',
        'transfer.please_review': 'Por favor revisa atentamente.',
        'transfer.operations': 'Operaciones',
        'transfer.no_memo': 'Sin Memo',
        'transfer.optional': '(Opcional)',
        // Receive Modal
        'receive.title': 'Recibir Fondos',
        'receive.scan_qr': 'Escanea el QR para recibir {chain} en esta cuenta',
        'receive.account_name': 'Nombre de Cuenta',
        'receive.copied': '¡Copiado!',
        'receive.copy': 'Copiar',
        'receive.close': 'Cerrar',
        // Manage Keys Extra
        'manage.label_posting': 'Clave Posting',
        'manage.label_active': 'Clave Active',
        'manage.label_memo': 'Clave Memo',
        // Import Errors Extra
        'import.error_username': 'Ingresa un usuario válido y existente.',
        'import.error_format': 'Una o más claves tienen un formato inválido.',
        'import.error_missing_key': 'Debes proveer al menos una clave privada.',
        'import.match_error_posting': 'La Clave Posting no coincide con la cuenta.',
        'import.match_error_active': 'La Clave Active no coincide con la cuenta.',
        'import.match_error_memo': 'La Clave Memo no coincide con la cuenta.',
        // Sign Request Extra
        'sign.expired': 'Solicitud expirada o no encontrada',
        'sign.active_key_missing': 'Falta Clave Activa',
        'sign.key_missing_type': 'Falta clave {type} para esta cuenta',
        'sign.key_missing_generic': 'Falta clave {type}',
        'sign.buffer_title': 'Firmar Mensaje',
        'sign.message_label': 'Mensaje',
        'sign.key_type': 'Clave',
        // Ayuda
        'help.title': 'Guía de Usuario',
        'help.keys_title': 'Gestión de Llaves',
        'help.keys_desc': 'La seguridad de su cuenta depende de sus llaves. Nunca comparta su Contraseña Maestra ni sus Llaves Privadas.',
        'help.posting_key_label': 'Llave Posting',
        'help.posting_key_desc': 'Úsela para acciones sociales como votar, publicar y seguir.',
        'help.active_key_label': 'Llave Activa',
        'help.active_key_desc': 'Necesaria para transacciones financieras como transferencias.',
        'help.memo_key_label': 'Llave Memo',
        'help.memo_key_desc': 'Utilizada para cifrar y descifrar mensajes privados.',
        'help.transactions_title': 'Transacciones',
        'help.transactions_desc': 'Gestione fácilmente sus activos en múltiples redes.',
        'help.transfers_point': 'Envíe fondos a cualquier usuario de forma segura.',
        'help.history_point': 'Vea transferencias entrantes y salientes.',
        'help.bulk_point': 'Use Transferencia Masiva para distribuciones múltiples.',
        'help.power_title': 'Poder (Power) y Staking',
        'help.power_desc': 'Ponga sus tokens a trabajar haciendo Staking (Power Up).',
        'help.power_point': 'Haga Power Up para aumentar su influencia de voto y ganar más recompensas.',
        'help.power_down_point': 'El Power Down convierte su Poder de nuevo en tokens durante 13 semanas.',
        'help.delegate_point': 'Delegue Poder a otros sin perder la propiedad de sus activos.',
        'help.savings_title': 'Ahorros y RCs',
        'help.savings_desc': 'Funciones avanzadas para Hive y Steem.',
        'help.savings_point': 'Deposite HBD/SBD en Ahorros para ganar intereses (aviso de retiro de 3 días).',
        'help.rc_point': 'Delegue Créditos de Recursos (solo Hive) para ayudar a otros usuarios.',
        'help.security_title': 'Seguridad ante todo',
        'help.security_desc': 'Las transacciones se firman localmente. Sus llaves nunca salen de su dispositivo sin cifrar.',
        'help.chat_title': 'Messenger Seguro',
        'help.chat_desc': 'Envía mensajes encriptados en la cadena.',
        'help.chat_warning': 'Mensajes públicos pero encriptados. Solo emisor/receptor pueden leer.',
        'help.chat_cost': 'Costo por mensaje: 0.001 (transferencia min)',
        // Help Buttons
        'help.btn_home': 'Volver a la pantalla principal para seleccionar red.',
        'help.btn_wallet': 'Acceder a sus cuentas, saldos y acciones.',
        'help.btn_bulk': 'Enviar fondos a múltiples cuentas en una sola transacción.',
        'help.btn_multisig': 'Gestionar cuentas multi-firma (Próximamente).',
        'help.btn_settings': 'Configurar cuentas, seguridad y preferencias.',
        'help.btn_lock': 'Bloquear su billetera inmediatamente.',
        'help.btn_detach': 'Abrir la billetera en una ventana flotante separada.',
        'help.btn_send': 'Transferir fondos a otro usuario.',
        'help.btn_receive': 'Mostrar código QR para recibir fondos.',
        'help.btn_history': 'Ver su historial de transacciones recientes.',
        'help.btn_keys': 'Ver y gestionar sus llaves privadas.',
        'help.btn_powerup': 'Convertir tokens a Power para aumentar influencia de voto.',
        'help.btn_powerdown': 'Iniciar el proceso de power down de 13 semanas.',
        'help.btn_delegate': 'Delegar tu Power a otra cuenta.',
        'help.btn_savings': 'Depositar stablecoins para ganar intereses (solo Hive/Steem).',
        'help.btn_rc': 'Delegar Créditos de Recursos para ayudar a otros a transaccionar (solo Hive).',
        // Operaciones de Power
        'power.powerup_title': 'Power Up',
        'power.powerdown_title': 'Power Down',
        'power.delegate_title': 'Delegar Power',
        'power.powerup_desc': 'Convertir {token} a {power} para aumentar tu poder de voto',
        'power.powerdown_desc': 'Iniciar power down de tu {power} (proceso de 13 semanas)',
        'power.delegate_desc': 'Delegar tu {power} a otra cuenta',
        'power.from_account': 'Desde Cuenta',
        'power.recipient': 'Destinatario',
        'power.recipient_placeholder': 'usuario',
        'power.recipient_hint': 'Deja tu usuario para hacer power up a ti mismo',
        'power.delegatee': 'Delegar A',
        'power.delegatee_placeholder': 'usuario',
        'power.amount_token': 'Cantidad ({token})',
        'power.amount_vests': 'Cantidad ({power})',
        'power.powerup_hint': 'Esto convertirá {token} a {power}',
        'power.powerdown_hint': 'Ingrese la cantidad en {power} para retirar',
        'power.delegate_hint': 'Ingrese la cantidad en {power} para delegar',
        'power.invalid_amount': 'Por favor ingresa una cantidad válida',
        'power.invalid_recipient': 'Por favor ingresa un destinatario válido',
        'power.active_key_required': 'Se requiere la clave activa para esta operación',
        'power.operation_failed': 'Operación fallida',
        'power.success': '¡Operación exitosa!',
        'power.stop_powerdown': 'Detener Power Down',
        'power.stop_powerdown_warning': 'Esto cancelará tu power down activo. Haz clic en Confirmar para proceder.',
        'power.available_power': '{power} Disponible',
        // Operaciones de Ahorros
        'savings.deposit_title': 'Depositar en Ahorros',
        'savings.withdraw_title': 'Retirar de Ahorros',
        'savings.deposit_desc': 'Gana intereses depositando {token} en ahorros',
        'savings.withdraw_desc': 'Retirar {token} de ahorros (período de espera de 3 días)',
        'savings.account': 'Cuenta',
        'savings.amount': 'Cantidad ({token})',
        'savings.deposit_hint': 'Los fondos estarán disponibles para retiro después de 3 días',
        'savings.withdraw_hint': 'El retiro se procesará después de 3 días',
        'savings.deposit_info': 'Los ahorros generan intereses y tienen un período de retiro de 3 días por seguridad',
        'savings.withdraw_info': 'Los retiros tardan 3 días en procesarse. Puedes cancelar durante este tiempo.',
        'savings.invalid_amount': 'Por favor ingresa una cantidad válida',
        'savings.active_key_required': 'Se requiere la clave activa para esta operación',
        'savings.operation_failed': 'Operación fallida',
        'savings.success': '¡Operación exitosa!',
        'savings.not_available': 'No Disponible',
        'savings.blurt_not_supported': 'Blurt no soporta la función de ahorros',

        // Operaciones de RC
        'rc.hive_only': 'La delegación de Créditos de Recursos (RC) solo está disponible en Hive.',
        'rc.delegate_title': 'Delegar RC',
        'rc.undelegate_title': 'Quitar Delegación RC',
        'rc.delegate_desc': 'Ayuda a cuentas nuevas delegándoles Créditos de Recursos.',
        'rc.undelegate_desc': 'Deja de delegar RC a una cuenta.',
        'rc.from_account': 'Desde la Cuenta',
        'rc.delegatee': 'Delegar a',
        'rc.delegatee_placeholder': 'usuario',
        'rc.max_rc': 'Cantidad de RC',
        'rc.max_rc_hint': 'Ingrese la cantidad de RC que desea delegar.',
        'rc.invalid_delegatee': 'Por favor ingrese un usuario válido',
        'rc.invalid_amount': 'Por favor ingrese una cantidad de RC válida',
        'rc.active_key_required': 'Se requiere la clave activa para delegar RC',
        'rc.operation_failed': 'La operación de RC falló',
        'rc.success': '¡Delegación de RC actualizada con éxito!',
        'rc.not_available': 'RC No Disponible',
        'rc.delegate_info': 'Delegar RC permite que las cuentas realicen más operaciones en Hive.',
        'rc.undelegate_info': 'Esto eliminará la delegación de RC de esta cuenta.',
    },
    fr: {
        'landing.welcome': 'Bon retour',
        'landing.subtitle': 'Sélectionnez un réseau pour gérer vos actifs',
        'landing.manage_keys': 'Gérer les clés',
        'landing.dapp_browser': 'Navigateur dApp',
        'wallet.active_key_tooltip': 'Clé Active présente',
        'wallet.posting_key_tooltip': 'Clé Posting présente',
        'wallet.refresh_tooltip': 'Actualiser les soldes',
        'wallet.send': 'Envoyer',
        'wallet.receive': 'Recevoir',
        'wallet.history': 'Historique',
        'wallet.keys': 'CLÉS',
        'wallet.network_label': 'Réseau Actif',
        'wallet.no_accounts_chain': 'Aucun compte ajouté pour {chain}',
        'wallet.add_one': 'Ajouter un compte',
        'bulk.analyze': 'Analyser la sécurité',
        'bulk.analyzing': 'Analyse en cours...',
        'bulk.success': 'Analyse : Aucun risque détecté.',
        'bulk.switch_network': 'Changer de réseau',
        // Sidebar
        'sidebar.home': 'Accueil',
        'sidebar.wallet': 'Portefeuille',
        'sidebar.bulk': 'Envoi Massif',
        'sidebar.multisig': 'MultiSig',
        'sidebar.manage': 'Paramètres',
        'sidebar.lock': 'Verrouiller',
        'sidebar.pin': 'Détacher Fenêtre',
        'sidebar.dock': 'Ancrer Fenêtre',
        'sidebar.language': 'Langue',
        // Actions
        'action.select_network': 'Sélectionner Réseau',
        'action.manage_keys': 'Gérer les clés',
        // Header
        'header.add': 'Ajouter un compte',
        'common.cancel': 'Annuler',
        'common.confirm': 'Confirmer',
        'common.close': 'Fermer',
        'common.processing': 'Traitement...',
        'common.recent_recipients': 'Destinataires Récents',
        'common.account_not_found': 'Compte non trouvé',
        // Import
        'import.title': 'Importer Portefeuille',
        'import.manual': 'Saisie Manuelle',
        'import.file': 'Téléverser Fichier',
        'import.select_chain': 'Sélectionner Chaîne',
        'import.username': 'Nom d\'utilisateur',
        'import.checking': 'Vérification chaîne...',
        'import.found': '✓ Trouvé',
        'import.not_found': 'Compte non trouvé',
        'import.private_keys': 'Clés Privées (Coller au moins une)',
        'import.key_posting': 'CLÉ POSTING',
        'import.key_active': 'CLÉ ACTIVE',
        'import.key_memo': 'CLÉ MEMO',
        'import.invalid_format': 'Format Invalide',
        'import.save': 'Enregistrer',
        'import.verifying': 'Vérification...',
        'import.placeholder_username': 'nom d\'utilisateur',
        'import.placeholder_key': 'Commence par 5...',
        'import.error_username': 'Veuillez entrer un nom d\'utilisateur valide.',
        'import.error_format': 'Une ou plusieurs clés ont un format invalide.',
        'import.error_missing_key': 'Vous devez fournir au moins une clé privée.',
        'import.match_error_posting': 'La clé Posting ne correspond pas au compte.',
        'import.match_error_active': 'La clé Active ne correspond pas au compte.',
        'import.match_error_memo': 'La clé Memo ne correspond pas au compte.',
        'import.success_file_parsed': 'Fichier analysé. Comptes : ',
        'import.error_file_read': 'Erreur de lecture du fichier.',
        'import.drag_drop': 'Glisser-déposer fichier JSON/CSV/TXT',
        'import.click_upload': 'ou cliquer pour téléverser',
        'import.processing': 'Traitement...',
        'import.bulk_summary': '{count} comptes importés.',
        'import.no_valid_accounts': 'Aucun compte valide trouvé.',
        // Settings
        'settings.title': 'Configurer votre portefeuille',
        'settings.accounts_title': 'Comptes Gérés',
        'settings.remove': 'Supprimer',
        'settings.add_new': 'Ajouter Nouveau Compte',
        'settings.no_accounts': 'Aucun compte trouvé.',
        'settings.security_title': 'Sécurité',
        'settings.change_password': 'Changer Mot de Passe',
        'settings.biometrics': 'Utiliser Biométrie',
        'settings.reset': 'Réinitialiser Portefeuille',
        // MultiSig
        'multisig.title': 'Portefeuille MultiSig',
        'multisig.initiator': 'Initiateur',
        'multisig.threshold': 'Seuil',
        'multisig.signers': 'Signataires',
        'multisig.proposal': 'Proposition',
        'multisig.expiration': 'Expiration',
        'multisig.create': 'Créer Proposition',
        'multisig.approve': 'Approuver',
        'multisig.construction_title': 'En Construction...',
        'multisig.construction_desc': 'Nous développons cette fonctionnalité pour assurer une sécurité maximale.',
        // Bulk
        'bulk.title': 'Transfert Massif',
        'bulk.recipients': 'Destinataires',
        'bulk.count': 'Nombre',
        'bulk.check': 'Vérifier Validité',
        'bulk.checking': 'Vérification...',
        'bulk.amount': 'Montant',
        'bulk.memo': 'Mémo',
        'bulk.same_amount': 'Même Montant',
        'bulk.diff_amount': 'Montants Différents',
        'bulk.add_row': '+ Ajouter Ligne',
        'bulk.verify': 'Vérifier',
        'bulk.import': 'Importer CSV/TXT',
        'bulk.total': 'Total',
        'bulk.sign_broadcast': 'Signer & Diffuser',
        'bulk.no_accounts': 'Aucun compte {chain} trouvé.',
        'bulk.sending_from': 'Envoi depuis',
        'bulk.asset': 'Actif :',
        'bulk.available': 'Disponible :',
        'bulk.title_single': 'Distribution Montant Unique',
        'bulk.title_multi': 'Distribution Montants Multiples',
        'bulk.validation_error': 'Erreur de Validation',
        'bulk.error_remove_invalid': 'Veuillez supprimer les comptes invalides avant d\'envoyer.',
        'bulk.success_title': 'Succès !',
        'bulk.success_msg': '{n} transferts envoyés avec succès. TXID : {txid}...',
        'bulk.error_title': 'Erreur',
        'bulk.error_failed': 'Échec de l\'envoi',
        'bulk.warn_not_found': '⚠ Attention : {n} utilisateur(s) non trouvé(s) sur la chaîne {chain}.',
        'bulk.error_no_active': 'Clé active non trouvée pour ce compte.',
        // Lock Screen
        'lock.title': 'Bon retour',
        'lock.unlock': 'Déverrouiller',
        'lock.password_placeholder': 'Entrer Mot de Passe',
        'lock.pin_placeholder': 'PIN à 6 chiffres',
        'lock.use_pin': 'Utiliser PIN',
        'lock.use_password': 'Utiliser Mot de Passe',
        'lock.biometrics': 'Déverrouiller avec Biométrie',
        'lock.reset': 'Réinitialiser',
        'lock.confirm_reset': 'Êtes-vous sûr ? Cela effacera toutes les données !',
        'lock.create_title': 'Créer Mot de Passe Maître',
        'lock.unlock_title': 'Déverrouiller votre Portefeuille',
        'lock.create_btn': 'Créer Portefeuille',
        'lock.unlock_btn': 'Déverrouiller',
        'lock.processing': 'Traitement...',
        'lock.placeholder_create': 'Définir Mot de Passe',
        'lock.placeholder_enter': 'Entrer Mot de Passe',
        'lock.error_length': 'Le mot de passe doit comporter au moins 8 caractères',
        'lock.or_sign_up': 'Ou s\'inscrire avec',
        'lock.or_unlock': 'Ou déverrouiller avec',
        'lock.clear_reset': 'Effacer Données Locales & Réinitialiser',
        'lock.session_expired': 'Session expirée. Veuillez déverrouiller pour enregistrer.',
        'lock.confirm_password': 'Confirmer le mot de passe',
        'lock.passwords_not_match': 'Les mots de passe ne correspondent pas',
        'lock.weak': 'Faible',
        'lock.medium': 'Moyen',
        'lock.strong': 'Fort',
        'lock.very_strong': 'Très Fort',
        'lock.security_strength': 'Sécurité',
        // Auth
        'auth.authenticator': 'Application d\'authentification (2FA)',
        'auth.configure_title': 'Configurer l\'authentification',
        'auth.scan_qr': 'Scannez ce QR code avec Aegis ou Google Auth.',
        'auth.enter_code': 'Entrez le code à 6 chiffres pour vérifier.',
        'auth.verify': 'Vérifier',
        'auth.success': 'Authentification configurée avec succès !',
        'auth.backup_code': 'Clé de secours (Saisie manuelle)',
        'auth.configure_desc': 'Configurer Aegis, Google Auth ou Authy',
        // Manage Account
        'manage.title': 'Gérer Compte',
        'manage.subtitle': '@{name} • {chain}',
        'manage.invalid_posting': 'Format Clé Posting Invalide',
        'manage.invalid_active': 'Format Clé Active Invalide',
        'manage.invalid_memo': 'Format Clé Memo Invalide',
        'manage.validating': 'Validation Clés...',
        'manage.save_verify': 'Enregistrer & Vérifier',
        'manage.remove_link': 'Supprimer Compte',
        'manage.verify_fail': 'Échec Validation Clé : ',
        'manage.success': 'Compte vérifié et enregistré !',
        'manage.confirm_remove_title': 'Supprimer @{name} ?',
        'manage.confirm_remove_desc': 'Ceci suprimera les clés localement. Irréversible.',
        'manage.cancel': 'Annuler',
        'manage.confirm_remove': 'Supprimer',
        'manage.label_posting': 'Clé Posting',
        'manage.label_active': 'Clé Active',
        'manage.label_memo': 'Clé Memo',
        'manage.add_posting': 'Ajouter Clé Privée Posting',
        'manage.add_active': 'Ajouter Clé Privée Active',
        'manage.add_memo': 'Ajouter Clé Privée Memo',
        // Security
        'security.analysis_prompt': 'Veuillez analyser cette transaction crypto pour les risques en Français : ',
        // History
        'history.title': 'Historique : {user}',
        'history.loading': 'Chargement historique...',
        'history.empty': 'Aucun transfert récent trouvé.',
        'history.received': 'Reçu',
        'history.sent': 'Envoyé',
        'history.from': 'De',
        'history.to': 'À',
        // Sign Request
        'sign.title': 'Demande de Signature',
        'sign.transfer_title': 'Demande de Transfert',
        'sign.vote_title': 'Demande de Vote',
        'sign.custom_json_title': 'JSON Personnalisé',
        'sign.operation': 'Opération',
        'sign.params': 'Paramètres',
        'sign.author': 'Auteur',
        'sign.weight': 'Poids',
        'sign.id': 'ID',
        'sign.json_payload': 'Contenu',
        'sign.from': 'De',
        'sign.to': 'À',
        'sign.reject': 'Rejeter',
        'sign.confirm': 'Confirmer',
        'sign.signing': 'Signature...',
        'sign.local_file': 'Fichier Local',
        'sign.unknown_source': 'Source Inconnue',
        'sign.loading': 'Chargement demande...',
        'sign.error': 'Erreur',
        'sign.account_not_found': 'Compte non trouvé dans ce portefeuille.',
        'sign.keys_missing': 'Clés manquantes pour ce compte.',
        'sign.active_key_missing': 'Clé Active manquante',
        'sign.key_missing_type': 'Clé {type} manquante pour ce compte',
        'sign.key_missing_generic': 'Clé {type} manquante',
        'sign.user_rejected': 'L\'utilisateur a rejeté la demande',
        'sign.success': 'Signé avec succès',
        'sign.trust_domain': 'Faire confiance à ce site',
        'sign.expired': 'Demande expirée ou non trouvée',
        'sign.buffer_title': 'Signer Message',
        'sign.message_label': 'Message',
        'sign.key_type': 'Clé',
        // Errors
        'validation.invalid_amount': 'Veuillez entrer un montant valide supérieur à 0.',
        'validation.required': 'Tous les champs sont requis.',
        'validation.account_not_found': 'Compte non trouvé sur {chain}',
        // Transfer
        'transfer.available': 'Disponible :',
        'transfer.memo_placeholder': 'Note publique',
        'transfer.review_title': 'Confirmer Transfert',
        'transfer.review_btn': 'Vérifier Transfert',
        'transfer.back': 'Retour',
        'transfer.total_amount': 'Montant Total',
        'transfer.per_user': 'Par Utilisateur :',
        'transfer.please_review': 'Veuillez vérifier attentivement.',
        'transfer.operations': 'Opérations',
        'transfer.no_memo': 'Pas de Mémo',
        'transfer.optional': '(Optionnel)',
        // Receive
        'receive.title': 'Recevoir des Fonds',
        'receive.scan_qr': 'Scannez le QR pour envoyer {chain} à ce compte',
        'receive.account_name': 'Nom du Compte',
        'receive.copied': 'Copié !',
        'receive.copy': 'Copier',
        'receive.close': 'Fermer',
        // Aide
        'help.title': 'Guide Utilisateur',
        'help.keys_title': 'Gestion des Clés',
        'help.keys_desc': 'La sécurité de votre compte dépend de vos clés. Ne partagez jamais votre mot de passe maître ou vos clés privées.',
        'help.posting_key_label': 'Clé Posting',
        'help.posting_key_desc': 'Utilisée pour les actions sociales comme voter, publier et suivre.',
        'help.active_key_label': 'Clé Active',
        'help.active_key_desc': 'Requise pour les transactions financières comme les transferts.',
        'help.memo_key_label': 'Clé Memo',
        'help.memo_key_desc': 'Utilisée pour chiffrer et déchiffrer les messages privés.',
        'help.transactions_title': 'Transactions',
        'help.transactions_desc': 'Gérez facilement vos actifs sur plusieurs réseaux.',
        'help.transfers_point': 'Envoyez des fonds en toute sécurité.',
        'help.history_point': 'Consultez les transferts entrants et sortants.',
        'help.bulk_point': 'Utilisez le Transfert Massif pour les distributions.',
        'help.security_title': 'Sécurité d\'abord',
        'help.security_desc': 'Les transactions sont signées localement. Vos clés restent chiffrées sur votre appareil.',
        'help.chat_title': 'Gravity Chat en Direct',
        'help.chat_desc': 'Messagerie en temps réel avec salons et MP.',
        'help.chat_warning': 'Ce chat utilise un ID unique séparé de vos portefeuilles.',
        'help.chat_cost': 'Gratuit & Instantané (Hors-chaîne)',
        // Help Buttons
        'help.btn_home': 'Retourner à l\'écran principal pour choisir un réseau.',
        'help.btn_wallet': 'Accéder à vos comptes, soldes et actions.',
        'help.btn_bulk': 'Envoyer des fonds à plusieurs comptes en une seule transaction.',
        'help.btn_multisig': 'Gérer les comptes multi-signatures (Bientôt).',
        'help.btn_settings': 'Configurer les comptes, la sécurité et les préférences.',
        'help.btn_lock': 'Verrouiller votre portefeuille immédiatement.',
        'help.btn_detach': 'Ouvrir le portefeuille dans une fenêtre flottante séparée.',
        'help.btn_send': 'Transférer des fonds à un autre utilisateur.',
        'help.btn_receive': 'Afficher le QR code pour recevoir des fonds.',
        'help.btn_history': 'Voir votre historique de transactions récent.',
        'help.btn_keys': 'Voir et gérer vos clés privées.',
    },
    de: {
        'landing.welcome': 'Willkommen zurück',
        'landing.subtitle': 'Wählen Sie ein Netzwerk zur Verwaltung Ihrer Assets',
        'landing.manage_keys': 'Schlüssel verwalten',
        'landing.dapp_browser': 'dApp Browser',
        'wallet.active_key_tooltip': 'Aktiver Schlüssel vorhanden',
        'wallet.posting_key_tooltip': 'Posting-Schlüssel vorhanden',
        'wallet.refresh_tooltip': 'Guthaben aktualisieren',
        'wallet.send': 'Senden',
        'wallet.receive': 'Empfangen',
        'wallet.history': 'Verlauf',
        'wallet.keys': 'SCHLÜSSEL',
        'wallet.network_label': 'Aktives Netzwerk',
        'wallet.no_accounts_chain': 'Keine Konten für {chain} hinzugefügt',
        'wallet.add_one': 'Konto hinzufügen',
        'bulk.analyze': 'Sicherheit analysieren',
        'bulk.analyzing': 'Analysiere...',
        'bulk.success': 'Analyse: Keine Risiken gefunden.',
        'bulk.switch_network': 'Netzwerk wechseln',
        // Sidebar
        'sidebar.home': 'Start',
        'sidebar.wallet': 'Wallet',
        'sidebar.bulk': 'Massenüberweisung',
        'sidebar.multisig': 'MultiSig',
        'sidebar.manage': 'Einstellungen',
        'sidebar.lock': 'Sperren',
        'sidebar.pin': 'Fenster lösen',
        'sidebar.dock': 'Fenster andocken',
        'sidebar.language': 'Sprache',
        // Actions
        'action.select_network': 'Netzwerk wählen',
        'action.manage_keys': 'Schlüssel verwalten',
        // Header
        'header.add': 'Konto hinzufügen',
        'common.cancel': 'Abbrechen',
        'common.confirm': 'Bestätigen',
        'common.close': 'Schließen',
        'common.processing': 'Verarbeitung...',
        'common.recent_recipients': 'Letzte Empfänger',
        'common.account_not_found': 'Konto nicht gefunden',
        // Import
        'import.title': 'Wallet importieren',
        'import.manual': 'Manuelle Eingabe',
        'import.file': 'Datei hochladen',
        'import.select_chain': 'Kette wählen',
        'import.username': 'Benutzername',
        'import.checking': 'Prüfe Kette...',
        'import.found': '✓ Gefunden',
        'import.not_found': 'Konto nicht gefunden',
        'import.private_keys': 'Private Schlüssel (Mindestens einen einfügen)',
        'import.key_posting': 'POSTING KEY',
        'import.key_active': 'ACTIVE KEY',
        'import.key_memo': 'MEMO KEY',
        'import.invalid_format': 'Ungültiges Format',
        'import.save': 'Konto speichern',
        'import.verifying': 'Verifiziere...',
        'import.placeholder_username': 'benutzername',
        'import.placeholder_key': 'Beginnt mit 5...',
        'import.error_username': 'Bitte geben Sie einen gültigen Benutzernamen ein.',
        'import.error_format': 'Ein oder mehrere Schlüssel haben ein ungültiges Format.',
        'import.error_missing_key': 'Sie müssen mindestens einen privaten Schlüssel angeben.',
        'import.match_error_posting': 'Posting-Schlüssel passt nicht zum Konto.',
        'import.match_error_active': 'Aktiver Schlüssel passt nicht zum Konto.',
        'import.match_error_memo': 'Memo-Schlüssel passt nicht zum Konto.',
        'import.success_file_parsed': 'Datei verarbeitet. Konten: ',
        'import.error_file_read': 'Fehler beim Lesen der Datei.',
        'import.drag_drop': 'JSON/CSV/TXT Datei hierher ziehen',
        'import.click_upload': 'oder klicken zum Hochladen',
        'import.processing': 'Verarbeite...',
        'import.bulk_summary': '{count} Konten importiert.',
        'import.no_valid_accounts': 'Keine gültigen Konten gefunden.',
        // Settings
        'settings.title': 'Wallet konfigurieren',
        'settings.accounts_title': 'Verwaltete Konten',
        'settings.remove': 'Entfernen',
        'settings.add_new': 'Neues Konto hinzufügen',
        'settings.no_accounts': 'Keine Konten gefunden.',
        'settings.security_title': 'Sicherheit',
        'settings.change_password': 'Passwort ändern',
        'settings.biometrics': 'Biometrie verwenden',
        'settings.reset': 'Wallet zurücksetzen',
        // MultiSig
        'multisig.title': 'MultiSig Wallet',
        'multisig.initiator': 'Initiator',
        'multisig.threshold': 'Schwelle',
        'multisig.signers': 'Unterzeichner',
        'multisig.proposal': 'Vorschlag',
        'multisig.expiration': 'Ablauf',
        'multisig.create': 'Vorschlag erstellen',
        'multisig.approve': 'Genehmigen',
        'multisig.construction_title': 'In Bau...',
        'multisig.construction_desc': 'Wir entwickeln diese Funktion für maximale Sicherheit.',
        // Bulk
        'bulk.title': 'Massenüberweisung',
        'bulk.recipients': 'Empfänger',
        'bulk.count': 'Anzahl',
        'bulk.check': 'Gültigkeit prüfen',
        'bulk.checking': 'Prüfe...',
        'bulk.amount': 'Betrag',
        'bulk.memo': 'Memo',
        'bulk.same_amount': 'Gleicher Betrag',
        'bulk.diff_amount': 'Unterschiedliche Beträge',
        'bulk.add_row': '+ Zeile hinzufügen',
        'bulk.verify': 'Verifizieren',
        'bulk.import': 'CSV/TXT importieren',
        'bulk.total': 'Gesamt',
        'bulk.sign_broadcast': 'Signieren & Senden',
        'bulk.no_accounts': 'Keine {chain} Konten gefunden.',
        'bulk.sending_from': 'Senden von',
        'bulk.asset': 'Asset:',
        'bulk.available': 'Verfügbar:',
        'bulk.title_single': 'Verteilung gleicher Betrag',
        'bulk.title_multi': 'Verteilung unterschiedliche Beträge',
        'bulk.validation_error': 'Validierungsfehler',
        'bulk.error_remove_invalid': 'Bitte entfernen Sie ungültige Konten vor dem Senden.',
        'bulk.success_title': 'Erfolg!',
        'bulk.success_msg': '{n} Überweisungen erfolgreich gesendet. TXID: {txid}...',
        'bulk.error_title': 'Fehler',
        'bulk.error_failed': 'Senden fehlgeschlagen',
        'bulk.warn_not_found': '⚠ Warnung: {n} Benutzer nicht auf der {chain} Chain gefunden.',
        'bulk.error_no_active': 'Aktiver Schlüssel für dieses Konto nicht gefunden.',
        // Lock Screen
        'lock.title': 'Willkommen zurück',
        'lock.unlock': 'Entsperren',
        'lock.password_placeholder': 'Passwort eingeben',
        'lock.pin_placeholder': '6-stellige PIN',
        'lock.use_pin': 'PIN verwenden',
        'lock.use_password': 'Passwort verwenden',
        'lock.biometrics': 'Mit Biometrie entsperren',
        'lock.reset': 'Zurücksetzen',
        'lock.confirm_reset': 'Sicher? Alle Daten werden gelöscht!',
        'lock.create_title': 'Master-Passwort erstellen',
        'lock.unlock_title': 'Wallet entsperren',
        'lock.create_btn': 'Wallet erstellen',
        'lock.unlock_btn': 'Entsperren',
        'lock.processing': 'Verarbeite...',
        'lock.placeholder_create': 'Passwort festlegen',
        'lock.placeholder_enter': 'Passwort eingeben',
        'lock.error_length': 'Passwort muss mindestens 8 Zeichen lang sein',
        'lock.or_sign_up': 'Oder registrieren mit',
        'lock.or_unlock': 'Oder entsperren mit',
        'lock.clear_reset': 'Lokale Daten löschen & Reset',
        'lock.session_expired': 'Sitzung abgelaufen. Bitte entsperren.',
        'lock.confirm_password': 'Passwort bestätigen',
        'lock.passwords_not_match': 'Passwörter stimmen nicht überein',
        'lock.weak': 'Schwach',
        'lock.medium': 'Mittel',
        'lock.strong': 'Stark',
        'lock.very_strong': 'Sehr Stark',
        'lock.security_strength': 'Sicherheit',
        // Auth
        'auth.authenticator': 'Authenticator App (2FA)',
        'auth.configure_title': 'Authenticator einrichten',
        'auth.scan_qr': 'Scannen Sie diesen QR-Code mit Aegis oder Google Auth.',
        'auth.enter_code': 'Geben Sie den 6-stelligen Code zur Überprüfung ein.',
        'auth.verify': 'Überprüfen',
        'auth.success': 'Authenticator erfolgreich konfiguriert!',
        'auth.backup_code': 'Backup-Schlüssel (Manuelle Eingabe)',
        'auth.configure_desc': 'Konfigurieren Sie Aegis, Google Auth oder Authy',
        // Manage Account
        'manage.title': 'Konto verwalten',
        'manage.subtitle': '@{name} • {chain}',
        'manage.invalid_posting': 'Ungültiges Posting-Key-Format',
        'manage.invalid_active': 'Ungültiges Active-Key-Format',
        'manage.invalid_memo': 'Ungültiges Memo-Key-Format',
        'manage.validating': 'Validiere Schlüssel...',
        'manage.save_verify': 'Speichern & Prüfen',
        'manage.remove_link': 'Konto entfernen',
        'manage.verify_fail': 'Schlüsselvalidierung fehlgeschlagen: ',
        'manage.success': 'Konto verifiziert und gespeichert!',
        'manage.confirm_remove_title': '@{name} entfernen?',
        'manage.confirm_remove_desc': 'Entfernt die Schlüssel. Kann nicht rückgängig gemacht werden.',
        'manage.cancel': 'Abbrechen',
        'manage.confirm_remove': 'Entfernen',
        'manage.label_posting': 'Posting-Schlüssel',
        'manage.label_active': 'Aktiver Schlüssel',
        'manage.label_memo': 'Memo-Schlüssel',
        'manage.add_posting': 'Posting-Schlüssel hinzufügen',
        'manage.add_active': 'Aktiven Schlüssel hinzufügen',
        'manage.add_memo': 'Memo-Schlüssel hinzufügen',
        // Security
        'security.analysis_prompt': 'Bitte analysieren Sie diese Krypto-Transaktion auf Risiken in Deutsch: ',
        // History
        'history.title': 'Verlauf: {user}',
        'history.loading': 'Lade Verlauf...',
        'history.empty': 'Keine kürzlichen Überweisungen gefunden.',
        'history.received': 'Empfangen',
        'history.sent': 'Gesendet',
        'history.from': 'Von',
        'history.to': 'An',
        // Sign Request
        'sign.title': 'Signaturanfrage',
        'sign.transfer_title': 'Überweisungsanfrage',
        'sign.vote_title': 'Abstimmungsanfrage',
        'sign.custom_json_title': 'Benutzerdefiniertes JSON',
        'sign.operation': 'Operation',
        'sign.params': 'Parameter',
        'sign.author': 'Autor',
        'sign.weight': 'Gewicht',
        'sign.id': 'ID',
        'sign.json_payload': 'Inhalt',
        'sign.from': 'Von',
        'sign.to': 'An',
        'sign.reject': 'Ablehnen',
        'sign.confirm': 'Bestätigen',
        'sign.signing': 'Signiere...',
        'sign.local_file': 'Lokale Datei',
        'sign.unknown_source': 'Unbekannte Quelle',
        'sign.loading': 'Lade Anfrage...',
        'sign.error': 'Fehler',
        'sign.account_not_found': 'Konto nicht in dieser Wallet gefunden.',
        'sign.keys_missing': 'Schlüssel fehlen für dieses Konto.',
        'sign.active_key_missing': 'Aktiver Schlüssel fehlt',
        'sign.key_missing_type': '{type}-Schlüssel fehlt für dieses Konto',
        'sign.key_missing_generic': '{type}-Schlüssel fehlt',
        'sign.user_rejected': 'Benutzer hat Anfrage abgelehnt',
        'sign.success': 'Erfolgreich signiert',
        'sign.trust_domain': 'Dieser Seite vertrauen',
        'sign.expired': 'Anfrage abgelaufen oder nicht gefunden',
        'sign.buffer_title': 'Nachricht signieren',
        'sign.message_label': 'Nachricht',
        'sign.key_type': 'Schlüssel',
        // Errors
        'validation.invalid_amount': 'Bitte geben Sie einen gültigen Betrag > 0 ein.',
        'validation.required': 'Alle Felder sind erforderlich.',
        'validation.account_not_found': 'Konto nicht auf {chain} gefunden',
        // Transfer
        'transfer.available': 'Verfügbar:',
        'transfer.memo_placeholder': 'Öffentliche Notiz',
        'transfer.review_title': 'Überweisung bestätigen',
        'transfer.review_btn': 'Überweisung prüfen',
        'transfer.back': 'Zurück',
        'transfer.total_amount': 'Gesamtbetrag',
        'transfer.per_user': 'Pro Benutzer:',
        'transfer.please_review': 'Bitte sorgfältig prüfen.',
        'transfer.operations': 'Operationen',
        'transfer.no_memo': 'Kein Memo',
        'transfer.optional': '(Optional)',
        // Receive
        'receive.title': 'Guthaben empfangen',
        'receive.scan_qr': 'QR scannen um {chain} an dieses Konto zu senden',
        'receive.account_name': 'Kontoname',
        'receive.copied': 'Kopiert!',
        'receive.copy': 'Kopieren',
        'receive.close': 'Schließen',
        // Hilfe
        'help.title': 'Benutzerhandbuch',
        'help.keys_title': 'Schlüsselverwaltung',
        'help.keys_desc': 'Ihre Kontosicherheit hängt von Ihren Schlüsseln ab. Teilen Sie niemals Ihr Master-Passwort oder Ihre privaten Schlüssel.',
        'help.posting_key_label': 'Posting-Schlüssel',
        'help.posting_key_desc': 'Verwenden Sie dies für soziale Aktionen wie Abstimmen und Posten.',
        'help.active_key_label': 'Aktiver Schlüssel',
        'help.active_key_desc': 'Erforderlich für Finanztransaktionen wie Überweisungen.',
        'help.memo_key_label': 'Memo-Schlüssel',
        'help.memo_key_desc': 'Wird zum Verschlüsseln und Entschlüsseln privater Nachrichten verwendet.',
        'help.transactions_title': 'Transaktionen',
        'help.transactions_desc': 'Verwalten Sie Ihre Assets einfach über mehrere Ketten hinweg.',
        'help.transfers_point': 'Senden Sie Gelder sicher an jeden Benutzer.',
        'help.history_point': 'Sehen Sie eingehende und ausgehende Überweisungen.',
        'help.bulk_point': 'Verwenden Sie Massenüberweisung für Verteilungen.',
        'help.security_title': 'Sicherheit zuerst',
        'help.security_desc': 'Transaktionen werden lokal signiert. Ihre Schlüssel verlassen Ihr Gerät nie unverschlüsselt.',
        'help.chat_title': 'Gravity Live Chat',
        'help.chat_desc': 'Echtzeit-Nachrichten mit Räumen und DMs.',
        'help.chat_warning': 'Dieser Chat verwendet eine eindeutige ID, getrennt von Ihren Wallets.',
        'help.chat_cost': 'Kostenlos & Sofort (Off-chain)',
        // Help Buttons
        'help.btn_home': 'Zurück zum Hauptbildschirm, um ein Netzwerk auszuwählen.',
        'help.btn_wallet': 'Zugriff auf Ihre Konten, Guthaben und Aktionen.',
        'help.btn_bulk': 'Senden Sie Gelder an mehrere Konten in einer einzigen Transaktion.',
        'help.btn_multisig': 'Multi-Signatur-Konten verwalten (Bald verfügbar).',
        'help.btn_settings': 'Konten, Sicherheit und Einstellungen konfigurieren.',
        'help.btn_lock': 'Ihr Wallet sofort sperren.',
        'help.btn_detach': 'Öffnen Sie das Wallet in einem separaten schwebenden Fenster.',
        'help.btn_send': 'Gelder an einen anderen Benutzer überweisen.',
        'help.btn_receive': 'QR-Code anzeigen, um Gelder zu empfangen.',
        'help.btn_history': 'Ihren letzten Transaktionsverlauf anzeigen.',
        'help.btn_keys': 'Ihre privaten Schlüssel anzeigen und verwalten.',
    },
    it: {
        'landing.welcome': 'Bentornato',
        'landing.subtitle': 'Seleziona una rete per gestire le tue risorse',
        'landing.manage_keys': 'Gestisci Chiavi',
        'landing.dapp_browser': 'Browser dApp',
        'wallet.active_key_tooltip': 'Chiave Attiva Presente',
        'wallet.posting_key_tooltip': 'Chiave Posting Presente',
        'wallet.refresh_tooltip': 'Aggiorna Saldi',
        'wallet.send': 'Invia',
        'wallet.receive': 'Ricevi',
        'wallet.history': 'Storico',
        'wallet.keys': 'CHIAVI',
        'wallet.network_label': 'Rete Attiva',
        'wallet.no_accounts_chain': 'Nessun account aggiunto per {chain}',
        'wallet.add_one': 'Aggiungi Account',
        'bulk.analyze': 'Analisi Sicurezza',
        'bulk.analyzing': 'Analisi in corso...',
        'bulk.success': 'Analisi: Nessun rischio rilevato.',
        'bulk.switch_network': 'Cambia Rete',
        // Sidebar
        'sidebar.home': 'Home',
        'sidebar.wallet': 'Portafoglio',
        'sidebar.bulk': 'Trasferimento Multiplo',
        'sidebar.multisig': 'MultiSig',
        'sidebar.manage': 'Impostazioni',
        'sidebar.lock': 'Blocca',
        'sidebar.pin': 'Stacca Finestra',
        'sidebar.dock': 'Ancora Finestra',
        'sidebar.language': 'Lingua',
        // Actions
        'action.select_network': 'Seleziona Rete',
        'action.manage_keys': 'Gestisci Chiavi',
        // Header
        'header.add': 'Aggiungi Account',
        'common.cancel': 'Annulla',
        'common.confirm': 'Conferma',
        'common.close': 'Chiudi',
        'common.processing': 'Elaborazione...',
        'common.recent_recipients': 'Destinatari Recenti',
        'common.account_not_found': 'Account non trovato',
        // Import
        'import.title': 'Importa Portafoglio',
        'import.manual': 'Inserimento Manuale',
        'import.file': 'Carica File',
        'import.select_chain': 'Seleziona Catena',
        'import.username': 'Nome Utente',
        'import.checking': 'Controllo catena...',
        'import.found': '✓ Trovato',
        'import.not_found': 'Account non trovato',
        'import.private_keys': 'Chiavi Private (Incolla almeno una)',
        'import.key_posting': 'CHIAVE POSTING',
        'import.key_active': 'CHIAVE ACTIVE',
        'import.key_memo': 'CHIAVE MEMO',
        'import.invalid_format': 'Formato Non Valido',
        'import.save': 'Salva Account',
        'import.verifying': 'Verifica...',
        'import.placeholder_username': 'nome utente',
        'import.placeholder_key': 'Inizia con 5...',
        'import.error_username': 'Inserisci un nome utente valido.',
        'import.error_format': 'Una o più chiavi hanno un formato non valido.',
        'import.error_missing_key': 'Devi fornire almeno una chiave privata.',
        'import.match_error_posting': 'La Chiave Posting non corrisponde all\'account.',
        'import.match_error_active': 'La Chiave Active non corrisponde all\'account.',
        'import.match_error_memo': 'La Chiave Memo non corrisponde all\'account.',
        'import.success_file_parsed': 'File analizzato. Account: ',
        'import.error_file_read': 'Errore lettura file.',
        'import.drag_drop': 'Trascina file JSON/CSV/TXT',
        'import.click_upload': 'o clicca per caricare',
        'import.processing': 'Elaborazione...',
        'import.bulk_summary': 'Importati {count} account.',
        'import.no_valid_accounts': 'Nessun account valido trovato.',
        // Settings
        'settings.title': 'Configura il tuo wallet',
        'settings.accounts_title': 'Account Gestiti',
        'settings.remove': 'Rimuovi',
        'settings.add_new': 'Aggiungi Nuovo Account',
        'settings.no_accounts': 'Nessun account trovato.',
        'settings.security_title': 'Sicurezza',
        'settings.change_password': 'Cambia Password',
        'settings.biometrics': 'Usa Biometria',
        'settings.reset': 'Reimposta Wallet',
        // MultiSig
        'multisig.title': 'Portafoglio MultiSig',
        'multisig.initiator': 'Iniziatore',
        'multisig.threshold': 'Soglia',
        'multisig.signers': 'Firmatari',
        'multisig.proposal': 'Proposta',
        'multisig.expiration': 'Scadenza',
        'multisig.create': 'Crea Proposta',
        'multisig.approve': 'Approva',
        'multisig.construction_title': 'In Costruzione...',
        'multisig.construction_desc': 'Stiamo costruendo questa funzionalità per garantire la massima sicurezza.',
        // Bulk
        'bulk.title': 'Trasferimento Multiplo',
        'bulk.recipients': 'Destinatari',
        'bulk.count': 'Conteggio',
        'bulk.check': 'Controlla Validità',
        'bulk.checking': 'Controllo...',
        'bulk.amount': 'Importo',
        'bulk.memo': 'Memo',
        'bulk.same_amount': 'Stesso Importo',
        'bulk.diff_amount': 'Importi Diversi',
        'bulk.add_row': '+ Aggiungi Riga',
        'bulk.verify': 'Verifica',
        'bulk.import': 'Importa CSV/TXT',
        'bulk.total': 'Totale',
        'bulk.sign_broadcast': 'Firma & Trasmetti',
        'bulk.no_accounts': 'Nessun account {chain} trovato.',
        'bulk.sending_from': 'Invio da',
        'bulk.asset': 'Asset:',
        'bulk.available': 'Disponibile:',
        'bulk.title_single': 'Distribuzione Stesso Importo',
        'bulk.title_multi': 'Distribuzione Importi Multipli',
        'bulk.validation_error': 'Errore di Validazione',
        'bulk.error_remove_invalid': 'Rimuovi gli account non validi prima di inviare.',
        'bulk.success_title': 'Successo!',
        'bulk.success_msg': 'Inviati {n} trasferimenti con successo. TXID: {txid}...',
        'bulk.error_title': 'Errore',
        'bulk.error_failed': 'Invio fallito',
        'bulk.warn_not_found': '⚠ Attenzione: {n} utente/i non trovato/i sulla catena {chain}.',
        'bulk.error_no_active': 'Chiave attiva non trovata per questo account.',
        // Lock Screen
        'lock.title': 'Bentornato',
        'lock.unlock': 'Sblocca Wallet',
        'lock.password_placeholder': 'Inserisci Password',
        'lock.pin_placeholder': 'PIN 6 cifre',
        'lock.use_pin': 'Usa PIN',
        'lock.use_password': 'Usa Password',
        'lock.biometrics': 'Sblocca con Biometria',
        'lock.reset': 'Reimposta',
        'lock.confirm_reset': 'Sei sicuro? Cancellerà tutti i dati!',
        'lock.create_title': 'Crea Password Principale',
        'lock.unlock_title': 'Sblocca il tuo Wallet',
        'lock.create_btn': 'Crea Wallet',
        'lock.unlock_btn': 'Sblocca',
        'lock.processing': 'Elaborazione...',
        'lock.placeholder_create': 'Imposta Password',
        'lock.placeholder_enter': 'Inserisci Password',
        'lock.error_length': 'La password deve essere di almeno 8 caratteri',
        'lock.or_sign_up': 'O registrati con',
        'lock.or_unlock': 'O sblocca con',
        'lock.clear_reset': 'Cancella Dati Locali & Reset',
        'lock.session_expired': 'Sessione scaduta. Sblocca per salvare.',
        'lock.confirm_password': 'Conferma Password',
        'lock.passwords_not_match': 'Le password non corrispondono',
        'lock.weak': 'Debole',
        'lock.medium': 'Media',
        'lock.strong': 'Forte',
        'lock.very_strong': 'Molto Forte',
        'lock.security_strength': 'Sicurezza',
        // Auth
        'auth.authenticator': 'App Autenticatore (2FA)',
        'auth.configure_title': 'Configura Autenticatore',
        'auth.scan_qr': 'Scansiona questo codice QR con Aegis o Google Auth.',
        'auth.enter_code': 'Inserisci il codice a 6 cifre per verificare.',
        'auth.verify': 'Verifica',
        'auth.success': 'Autenticatore configurato con successo!',
        'auth.backup_code': 'Chiave di Backup (Inserimento Manuale)',
        'auth.configure_desc': 'Configura Aegis, Google Auth o Authy',
        // Manage Account
        'manage.title': 'Gestisci Account',
        'manage.subtitle': '@{name} • {chain}',
        'manage.invalid_posting': 'Formato Chiave Posting Invalido',
        'manage.invalid_active': 'Formato Chiave Active Invalido',
        'manage.invalid_memo': 'Formato Chiave Memo Invalido',
        'manage.validating': 'Validazione Chiavi...',
        'manage.save_verify': 'Salva & Verifica',
        'manage.remove_link': 'Rimuovi Account',
        'manage.verify_fail': 'Validazione Chiave Fallita: ',
        'manage.success': 'Account verificato e salvato!',
        'manage.confirm_remove_title': 'Rimuovere @{name}?',
        'manage.confirm_remove_desc': 'Questo rimuoverà le chiavi dell\'account. Non si può annullare.',
        'manage.cancel': 'Annulla',
        'manage.confirm_remove': 'Rimuovi',
        'manage.label_posting': 'Chiave Posting',
        'manage.label_active': 'Chiave Active',
        'manage.label_memo': 'Chiave Memo',
        'manage.add_posting': 'Aggiungi Chiave Privata Posting',
        'manage.add_active': 'Aggiungi Chiave Privata Active',
        'manage.add_memo': 'Aggiungi Chiave Privata Memo',
        // Security
        'security.analysis_prompt': 'Per favore analizza questa transazione crypto per rischi in Italiano: ',
        // History
        'history.title': 'Cronologia: {user}',
        'history.loading': 'Caricamento cronologia...',
        'history.empty': 'Nessun trasferimento recente trovato.',
        'history.received': 'Ricevuto',
        'history.sent': 'Inviato',
        'history.from': 'Da',
        'history.to': 'A',
        // Sign Request
        'sign.title': 'Richiesta Firma',
        'sign.transfer_title': 'Richiesta Trasferimento',
        'sign.vote_title': 'Richiesta Voto',
        'sign.custom_json_title': 'JSON Personalizzato',
        'sign.operation': 'Operazione',
        'sign.params': 'Parametri',
        'sign.author': 'Autore',
        'sign.weight': 'Peso',
        'sign.id': 'ID',
        'sign.json_payload': 'Contenuto',
        'sign.from': 'Da',
        'sign.to': 'A',
        'sign.reject': 'Rifiuta',
        'sign.confirm': 'Conferma',
        'sign.signing': 'Firma in corso...',
        'sign.local_file': 'File Locale',
        'sign.unknown_source': 'Fonte Sconosciuta',
        'sign.loading': 'Caricamento richiesta...',
        'sign.error': 'Errore',
        'sign.account_not_found': 'Account non trovato in questo wallet.',
        'sign.keys_missing': 'Chiavi mancanti per questo account.',
        'sign.active_key_missing': 'Chiave Attiva mancante',
        'sign.key_missing_type': 'Chiave {type} mancante per questo account',
        'sign.key_missing_generic': 'Chiave {type} mancante',
        'sign.user_rejected': 'L\'utente ha rifiutato la richiesta',
        'sign.success': 'Firmato con successo',
        'sign.trust_domain': 'Fidati di questo sito',
        'sign.expired': 'Richiesta scaduta o non trovata',
        'sign.buffer_title': 'Firma Messaggio',
        'sign.message_label': 'Messaggio',
        'sign.key_type': 'Chiave',
        // Errors
        'validation.invalid_amount': 'Inserisci un importo valido maggiore di 0.',
        'validation.required': 'Tutti i campi sono obbligatori.',
        'validation.account_not_found': 'Account non trovato su {chain}',
        // Transfer
        'transfer.available': 'Disponibile:',
        'transfer.memo_placeholder': 'Nota pubblica',
        'transfer.review_title': 'Conferma Trasferimento',
        'transfer.review_btn': 'Revisiona Trasferimento',
        'transfer.back': 'Indietro',
        'transfer.total_amount': 'Importo Totale',
        'transfer.per_user': 'Per Utente:',
        'transfer.please_review': 'Per favore controlla attentamente.',
        'transfer.operations': 'Operazioni',
        'transfer.no_memo': 'Nessun Memo',
        'transfer.optional': '(Opzionale)',
        // Receive
        'receive.title': 'Ricevi Fondi',
        'receive.scan_qr': 'Scansiona il QR per inviare {chain} a questo account',
        'receive.account_name': 'Nome Account',
        'receive.copied': 'Copiato!',
        'receive.copy': 'Copia',
        'receive.close': 'Chiudi',
        // Aiuto
        'help.title': 'Guida Utente',
        'help.keys_title': 'Gestione Chiavi',
        'help.keys_desc': 'La sicurezza del tuo account dipende dalle tue chiavi. Non condividere mai la Password Principale o le Chiavi Private.',
        'help.posting_key_label': 'Chiave Posting',
        'help.posting_key_desc': 'Usalo per azioni sociali come votare, pubblicare e seguire.',
        'help.active_key_label': 'Chiave Attiva',
        'help.active_key_desc': 'Richiesta per transazioni finanziarie come i trasferimenti.',
        'help.memo_key_label': 'Chiave Memo',
        'help.memo_key_desc': 'Usata per crittografare e decrittografare messaggi privati.',
        'help.transactions_title': 'Transazioni',
        'help.transactions_desc': 'Gestisci facilmente le tue risorse su più reti.',
        'help.transfers_point': 'Invia fondi a qualsiasi utente in modo sicuro.',
        'help.history_point': 'Visualizza trasferimenti in entrata e in uscita.',
        'help.bulk_point': 'Usa Trasferimento Multiplo per distribuzioni di massa.',
        'help.security_title': 'Sicurezza prima di tutto',
        'help.security_desc': 'Le transazioni vengono firmate localmente. Le tue chiavi non lasciano mai il dispositivo non crittografate.',
        'help.chat_title': 'Gravity Chat Live',
        'help.chat_desc': 'Messaggistica in tempo reale con stanze e DM.',
        'help.chat_warning': 'Questa chat usa un ID univoco separato dai tuoi wallet.',
        'help.chat_cost': 'Gratis e Istantaneo (Off-chain)',
        // Help Buttons
        'help.btn_home': 'Torna alla schermata principale per selezionare una rete.',
        'help.btn_wallet': 'Accedi ai tuoi account, saldi e azioni.',
        'help.btn_bulk': 'Invia fondi a più account in una singola transazione.',
        'help.btn_multisig': 'Gestisci account multi-firma (Prossimamente).',
        'help.btn_settings': 'Configura account, sicurezza e preferenze.',
        'help.btn_lock': 'Blocca immediatamente il tuo wallet.',
        'help.btn_detach': 'Apri il wallet in una finestra mobile separata.',
        'help.btn_send': 'Trasferisci fondi a un altro utente.',
        'help.btn_receive': 'Mostra codice QR per ricevere fondi.',
        'help.btn_history': 'Visualizza la cronologia delle transazioni recenti.',
        'help.btn_keys': 'Visualizza e gestisci le tue chiavi private.',
    },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('en');

    // Load verified language from storage if available
    useEffect(() => {
        if (typeof chrome !== 'undefined' && chrome.storage) {
            chrome.storage.local.get(['language'], (res: any) => {
                const supported = ['en', 'es', 'fr', 'de', 'it'];
                if (res.language && supported.includes(res.language)) {
                    setLanguage(res.language);
                }
            });
        }
    }, []);

    const changeLanguage = (lang: Language) => {
        setLanguage(lang);
        if (typeof chrome !== 'undefined' && chrome.storage) {
            chrome.storage.local.set({ language: lang });
        }
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useTranslation = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useTranslation must be used within a LanguageProvider');
    }
    return context;
};
